services:
  # API Service
  - type: web
    name: deyncare-api
    env: docker
    plan: free
    healthCheckPath: /api/health
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      # Database
      - key: MONGODB_URI
        sync: false
      # JWT Settings
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRY
        value: 15m
      - key: JWT_REFRESH_EXPIRY
        value: 30d
      # CORS Settings
      - key: CORS_ORIGIN
        value: "*" # Update with your frontend URL in production
      # Email Configuration
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      # Admin Creation
      - key: CREATE_SUPER_ADMIN
        value: false # Set to true only for initial deployment
      - key: SUPER_ADMIN_EMAIL
        sync: false
      - key: SUPER_ADMIN_PASSWORD
        sync: false
      - key: SUPER_ADMIN_NAME
        sync: false
      - key: SUPER_ADMIN_PHONE
        sync: false
      # Scheduler
      - key: ENABLE_SCHEDULER
        value: true # Enable in-app scheduler on Render
